export const  bestSeller=[
    {       
            id:1,
            category:'bestSellers',
            productName: "Onion (Loose)",
            brandName:'Fresho',
            rate: [61.84,30.02,153.29],
            dicountedRate:[43,21.50,106],
            offer:30,
            price:61.84,
            discountedPrice:43,
            weight:'2 kg - Rs 43.00',
            imageUrl: "https://www.bigbasket.com/media/uploads/p/s/40075537_5-fresho-onion.jpg",
            weightPakages:['2 kg - Rs 43.00','1 kg - Rs 21.50','5 kg - Rs 105'],
            addTocardAuthendication:false,
            quantity:1
    },
    {       
            id:2,
            category:'bestSellers',
            productName: "Farm Eggs - Regular, Medium, Antibiotic Residue-Free",
            brandName:'Fresho',
            rate: [],
            dicountedRate:[],
            offer:35,
            price:65,
            discountedPrice:42,
            weight:'6 pcs-Rs 42.00',
            imageUrl: 'https://www.bigbasket.com/media/uploads/p/s/281204_9-fresho-farm-eggs-regular-medium-antibiotic-residue-free.jpg',
            weightPakages:[],
            addTocardAuthendication:false,
            quantity:1
    },
    {       
            id:3,
            category:'bestSellers',
            productName: "Farm Eggs - Table Tray, Medium, Antibiotic Residue-Free",
            brandName:'Fresho',
            rate: [140,265],
            dicountedRate:[105,229],
            offer:25,
            price:140,
            discountedPrice:105,
            weight:'12 pcs - Rs 105.00',
            imageUrl: 'https://www.bigbasket.com/media/uploads/p/s/40072320_2-fresho-farm-eggs-table-tray-medium-antibiotic-residue-free.jpg',
            weightPakages:['12 pcs - Rs 105.00','30 pcs - Rs 229.00'],
            addTocardAuthendication:false,
            quantity:1
    },
    {       
            id:4,
            category:'bestSellers',
            productName: "Peanut Filled Chocolate Bar",
            brandName:'Fresho',
            rate: [50,150,153.29],
            dicountedRate:[30,90,17.50],
            offer:40,
            price:50,
            discountedPrice:30,
            weight:'45 g Pouch - Rs 30.00',
            imageUrl: "	https://www.bigbasket.com/media/uploads/p/s/251209_14-snickers-peanut-filled-chocolate-bar.jpg",
            weightPakages:['45 g Pouch - Rs 30.00','3x45 g Pouch - Rs 90.00','22 g Pouch - Rs 17.50'],
            addTocardAuthendication:false,
            quantity:1
    },
    {       
            id:5,
            category:'bestSellers',
            productName: "Tender Coconut",
            brandName:'Fresho',
            rate: [52.63,157.89],
            dicountedRate:[38,114],
            offer:28,
            price:52.63,
            discountedPrice:38,
            weight:'1 pc-Rs 38.00',
            imageUrl: "	https://www.bigbasket.com/media/uploads/p/s/40057966_3-fresho-tender-coconut-medium.jpg",
            weightPakages:['1 pc-Rs 38.00','3 pcs-Rs 114'],
            addTocardAuthendication:false,
            quantity:1
    },
    {       
            id:6,
            category:'bestSellers',
            productName: "Original Extra Virgin Olive Oil",
            brandName:'BORGES',
            rate: [2700,1400,6000],
            dicountedRate:[1512,798.00,3660],
            offer:44,
            price:2700,
            discountedPrice:1512.00,
            weight:'2 L PET Bottle - Rs 1512',
            imageUrl: "https://www.bigbasket.com/media/uploads/p/s/40191534_1-borges-extra-virgin-olive-oil.jpg",
            weightPakages:['2 L PET Bottle - Rs 1512','1 L PET Bottle - Rs 798.00','5 L PET Bottle - Rs 3660.00'],
            addTocardAuthendication:false,
            quantity:1
    },
    {       
            id:7,
            category:'bestSellers',
            productName: "Refined Sunflower Oil",
            brandName:'Sunpure',
            rate: [185,555],
            dicountedRate:[134.00,402.00],
            offer:28,
            price:185,
            discountedPrice:134.00,
            weight:'1 L Pouch -Rs 134.00',
            imageUrl: "https://www.bigbasket.com/media/uploads/p/s/274120_6-sunpure-refined-sunflower-oil.jpg",
            weightPakages:['1 L Pouch -Rs 134.00','3x1 L Pouch -Rs 402.00'],
            addTocardAuthendication:false,
            quantity:1
    },
    {       
            id:8,
            category:'bestSellers',
            productName: "Fresho Pomegranate Regular",
            brandName:'Fresho',
            rate: [],
            dicountedRate:[],
            offer:44,
            price:239.47,
            discountedPrice:135,
            weight:'1 kg (5-6 pcs per kg)',
            imageUrl: "	https://www.bigbasket.com/media/uploads/p/s/40120006_5-fresho-pomegranate-small.jpg",
            weightPakages:[],
            addTocardAuthendication:false,
            quantity:1
    },
    {       
            id:9,
            category:'bestSellers',
            productName: "Grapes - Green Sonaka",
            brandName:'Fresho',
            rate: [],
            dicountedRate:[],
            offer:38,
            price:50,
            discountedPrice:31,
            weight:'approx 500 g 1 Pack',
            imageUrl: "https://www.bigbasket.com/media/uploads/p/s/40218332_1-fresho-grapes-green.jpg",
            weightPakages:[],
            addTocardAuthendication:false,
            quantity:1
    },
    {       
            id:10,
            category:'bestSellers',
            productName: "Broccoli",
            brandName:'Fresho',
            rate: [],
            dicountedRate:[],
            offer:41,
            price:46.05,
            discountedPrice:27,
            weight:'1 pc (Approx 250g-500g)',
            imageUrl: "	https://www.bigbasket.com/media/uploads/p/s/10000063_20-fresho-broccoli.jpg",
            weightPakages:[],
            addTocardAuthendication:false,
            quantity:1
    },
    {       
            id:11,
            category:'bestSellers',
            productName: "Beetroot (Loose)",
            brandName:'Fresho',
            rate: [24.34,48.68,12.17],
            dicountedRate:[14.50,29.00,7.50],
            offer:40,
            price:24.34,
            discountedPrice:14.50,
            weight:'500 g-Rs 14.50',
            imageUrl: "https://www.bigbasket.com/media/uploads/p/s/10000047_21-fresho-beetroot.jpg",
            weightPakages:['500 g-Rs 14.50','1 kg-Rs 29.00','250 kg-Rs 7.50'],
            addTocardAuthendication:false,
            quantity:1
    },
    {       
            id:12,
            category:'bestSellers',
            productName: "Chicken - Curry Cut Without Skin, Antibiotic Residue Free, 12-16 Pcs",
            brandName:'Fresho',
            rate: [207,363,181],
            dicountedRate:[149.00,269.00,119.00],
            offer:28,
            price:207,
            discountedPrice:149,
            weight:'500 g - Rs 149.00',
            imageUrl:'https://www.bigbasket.com/media/uploads/p/s/40048898_5-fresho-chicken-curry-cut-without-skin-antibiotic-residue-free.jpg',
            weightPakages:['500 g - Rs 149.00','1 kg -Rs 269.00','250 kg -Rs 119.00'],
            addTocardAuthendication:false,
            quantity:1
    },
    {       
            id:13,
            category:'bestSellers',
            productName: "Urad Dal/Uddina Bele - Split",
            brandName:'BB Popular',
            rate: [100,200],
            dicountedRate:[69,136],
            offer:31,
            price:100,
            discountedPrice:69,
            weight:'500 g Pouch- Rs 69.00',
            imageUrl: "https://www.bigbasket.com/media/uploads/p/s/30010377_11-bb-popular-urad-dal-split.jpg",
            weightPakages:['500 g Pouch- Rs 69.00','1 kg Pouch- Rs 136.00'],
            addTocardAuthendication:false,
            quantity:1
    },
    {       
            id:14,
            category:'bestSellers',
            productName: "Carbon Zinc Battery Red HD AA 1015",
            brandName:'Fresho',
            rate: [180,360],
            dicountedRate:[126.00,229.00],
            offer:36,
            price:180,
            discountedPrice:126,
            weight:'10 pcs - Rs 126.00',
            imageUrl: "	https://www.bigbasket.com/media/uploads/p/s/106417_2-eveready-carbon-zinc-battery-red-hd-aa-1015.jpg",
            weightPakages:['10 pcs - Rs 126.00','20 pcs - Rs 229.00'],
            addTocardAuthendication:false,
            quantity:1
    },


]