export const vegetables=[
    {
        id: 1,
        category:'friutsAndVegetables',
        productName: 'Chilli - Green, Organically Grown (Loose)',
        brandName:'Fresho',
        rate: [30.47,157.89,15.79], 
        dicountedRate:[30,120,12],
        offer: 24,
        price: 30.47,
        discountedPrice: 30,
        weight:'250 g - Rs 30.00',
        imageUrl: '	https://www.bigbasket.com/media/uploads/p/s/50000511_7-fresho-chilli-green-organically-grown.jpg',
        weightPakages:['250 g - Rs 30.00','1 kg - Rs 120.00','100 g - Rs 12.00'],
        addTocardAuthendication:false,
        quantity:1
    },
    {
        id: 2,
        category:'friutsAndVegetables',
        productName: 'Ginger - Organically Grown (Loose)',
        brandName:'Fresho',
        rate: [42.76,171.05,17.11],
        dicountedRate:[32.50,130,13],
        offer: 24,
        price: 42.76,
        discountedPrice: 32.50,
        weight: '250 g - Rs 32.50',
        imageUrl: '	https://www.bigbasket.com/media/uploads/p/s/50000509_5-fresho-ginger-organically-grown.jpg',
        weightPakages:['250 g - Rs 32.50','1 kg - Rs 130.00','100 g - Rs 13.00'],
        addTocardAuthendication:false,
        quantity:1
    },
    {
        id: 3,
        category:'friutsAndVegetables',
        productName: 'Tomato - Local, Organically Grown (Loose)',
        brandName:'Fresho',
        rate: [26.32,13.16],
        dicountedRate:[20,10],
        offer: 24,
        price: 26.32,
        discountedPrice: 20,
        weight:'1 kg - Rs 20.00',
        imageUrl: '	https://www.bigbasket.com/media/uploads/p/s/40022638_4-fresho-tomato-local-organically-grown.jpg',
        weightPakages:['1 kg - Rs 20.00','500 g - Rs 10.00'],
        addTocardAuthendication:false,
        quantity:1
    },
    {
        id: 4,
        category:'friutsAndVegetables',
        productName: 'Banana - Yelakki, Organically Grown',
        brandName:'Fresho',
        rate: [164.47,82.89],
        dicountedRate:[125,63],
        offer: 24,
        price: 164.47,
        discountedPrice: 125,
        weight:'1 kg - Rs 125.00',
        imageUrl: '	https://www.bigbasket.com/media/uploads/p/s/50000457_4-fresho-banana-yelakki-organically-grown.jpg',
        weightPakages:['1 kg - Rs 125.00','500 g - Rs 63.00'],
        addTocardAuthendication:false,
        quantity:1
    },
    {
        id: 5,
        category:'friutsAndVegetables',
        productName: 'Amla (Loose)',
        brandName:'Fresho',
        rate: [184.21,46.05,92.11,18.42],
        dicountedRate:[140,35,70,14],
        offer: 24,
        price: 184.21,
        discountedPrice: 140,
        weight:'1 kg - Rs 140.00',
        imageUrl: '	https://www.bigbasket.com/media/uploads/p/s/40004383_13-fresho-amla.jpg',
        weightPakages:['1 kg - Rs 140.00','250 g - Rs 35.00','500 g - Rs 70.00','100 g - Rs 14.00'],
        addTocardAuthendication:false,
        quantity:1
    },
    {
        id: 6,
        category:'friutsAndVegetables',
        productName: 'Cucumber - Organically Grown (Loose)',
        brandName:'Fresho',
        rate: [31.58,15.79],
        dicountedRate:[24,12],
        offer: 24,
        price: 31.58,
        discountedPrice: 24,
        weight:'1 kg - Rs 24.00',
        imageUrl: 'https://www.bigbasket.com/media/uploads/p/l/40022639_5-fresho-cucumber-organically-grown.jpg',
        weightPakages:['1 kg - Rs 24.00','500 g - Rs 12.00'],
        addTocardAuthendication:false,
        quantity:1
    },
    {
        id: 7,
        category:'friutsAndVegetables',
        productName: 'Beans - Organically Grown (Loose)',
        brandName:'Fresho',
        rate: [],
        dicountedRate:[],
        offer: 24,
        price: 98.68,
        discountedPrice: 75,
        weight:'500 g - Rs 75',
        imageUrl: 'https://www.bigbasket.com/media/uploads/p/l/40023469_7-fresho-beans-organically-grown.jpg',
        weightPakages:[],
        addTocardAuthendication:false,
        quantity:1
    },
    // {
    //     id: 8,
    //     category:'friutsAndVegetables',
    //     productName: '',
    //     brandName:'',
    //     rate: [],
    //     dicountedRate:[],
    //     offer: ,
    //     price:,
    //     discountedPrice:,
    //     weight:'',
    //     imageUrl: '',
    //     weightPakages:[],
    //     addTocardAuthendication:false,
    //     quantity:1
    // },
    // {
    //     id: 9,
    //     category:'friutsAndVegetables',
    //     productName: '',
    //     brandName:'',
    //     rate: [],
    //     dicountedRate:[],
    //     offer: ,
    //     price:,
    //     discountedPrice:,
    //     weight:'',
    //     imageUrl: '',
    //     weightPakages:[],
    //     addTocardAuthendication:false,
    //     quantity:1
    // },
    // {
    //     id: 10,
    //     category:'friutsAndVegetables',
    //     productName: '',
    //     brandName:'',
    //     rate: [],
    //     dicountedRate:[],
    //     offer: ,
    //     price:,
    //     discountedPrice:,
    //     weight:'',
    //     imageUrl: '',
    //     weightPakages:[],
    //     addTocardAuthendication:false,
    //     quantity:1
    // },
    // {
    //     id: 11,
    //     category:'friutsAndVegetables',
    //     productName: '',
    //     brandName:'',
    //     rate: [],
    //     dicountedRate:[],
    //     offer: ,
    //     price:,
    //     discountedPrice:,
    //     weight:'',
    //     imageUrl: '',
    //     weightPakages:[],
    //     addTocardAuthendication:false,
    //     quantity:1
    // },
    // {
    //     id: 12,
    //     category:'friutsAndVegetables',
    //     productName: '',
    //     brandName:'',
    //     rate: [],
    //     dicountedRate:[],
    //     offer: ,
    //     price:,
    //     discountedPrice:,
    //     weight:'',
    //     imageUrl: '',
    //     weightPakages:[],
    //     addTocardAuthendication:false,
    //     quantity:1
    // },
    // {
    //     id: 13,
    //     category:'friutsAndVegetables',
    //     productName: '',
    //     brandName:'',
    //     rate: [],
    //     dicountedRate:[],
    //     offer: ,
    //     price:,
    //     discountedPrice:,
    //     weight:'',
    //     imageUrl: '',
    //     weightPakages:[],
    //     addTocardAuthendication:false,
    //     quantity:1
    // },
    // {
    //     id: 14,
    //     category:'friutsAndVegetables',
    //     productName: '',
    //     brandName:'',
    //     rate: [],
    //     dicountedRate:[],
    //     offer: ,
    //     price:,
    //     discountedPrice:,
    //     weight:'',
    //     imageUrl: '',
    //     weightPakages:[],
    //     addTocardAuthendication:false,
    //     quantity:1
    // },
    // {
    //     id: 15,
    //     category:'friutsAndVegetables',
    //     productName: '',
    //     brandName:'',
    //     rate: [],
    //     dicountedRate:[],
    //     offer: ,
    //     price:,
    //     discountedPrice:,
    //     weight:'',
    //     imageUrl: '',
    //     weightPakages:[],
    //     addTocardAuthendication:false,
    //     quantity:1
    // },
    // {
    //     id: 16,
    //     category:'friutsAndVegetables',
    //     productName: '',
    //     brandName:'',
    //     rate: [],
    //     dicountedRate:[],
    //     offer: ,
    //     price:,
    //     discountedPrice:,
    //     weight:'',
    //     imageUrl: '',
    //     weightPakages:[],
    //     addTocardAuthendication:false,
    //     quantity:1
    // },
    // {
    //     id: 17,
    //     category:'friutsAndVegetables',
    //     productName: '',
    //     brandName:'',
    //     rate: [],
    //     dicountedRate:[],
    //     offer: ,
    //     price:,
    //     discountedPrice:,
    //     weight:'',
    //     imageUrl: '',
    //     weightPakages:[],
    //     addTocardAuthendication:false,
    //     quantity:1
    // },
    // {
    //     id: 18,
    //     category:'friutsAndVegetables',
    //     productName: '',
    //     brandName:'',
    //     rate: [],
    //     dicountedRate:[],
    //     offer: ,
    //     price:,
    //     discountedPrice:,
    //     weight:'',
    //     imageUrl: '',
    //     weightPakages:[],
    //     addTocardAuthendication:false,
    //     quantity:1
    // },
    // {
    //     id: 19,
    //     category:'friutsAndVegetables',
    //     productName: '',
    //     brandName:'',
    //     rate: [],
    //     dicountedRate:[],
    //     offer: ,
    //     price:,
    //     discountedPrice:,
    //     weight:'',
    //     imageUrl: '',
    //     weightPakages:[],
    //     addTocardAuthendication:false,
    //     quantity:1
    // },
    // {
    //     id: 20,
    //     category:'friutsAndVegetables',
    //     productName: '',
    //     brandName:'',
    //     rate: [],
    //     dicountedRate:[],
    //     offer: ,
    //     price:,
    //     discountedPrice:,
    //     weight:'',
    //     imageUrl: '',
    //     weightPakages:[],
    //     addTocardAuthendication:false,
    //     quantity:1
    // },
    // {
    //     id: 21,
    //     category:'friutsAndVegetables',
    //     productName: '',
    //     brandName:'',
    //     rate: [],
    //     dicountedRate:[],
    //     offer: ,
    //     price:,
    //     discountedPrice:,
    //     weight:'',
    //     imageUrl: '',
    //     weightPakages:[],
    //     addTocardAuthendication:false,
    //     quantity:1
    // },
    // {
    //     id: 22,
    //     category:'friutsAndVegetables',
    //     productName: '',
    //     brandName:'',
    //     rate: [],
    //     dicountedRate:[],
    //     offer: ,
    //     price:,
    //     discountedPrice:,
    //     weight:'',
    //     imageUrl: '',
    //     weightPakages:[],
    //     addTocardAuthendication:false,
    //     quantity:1
    // },
    // {
    //     id: 23,
    //     category:'friutsAndVegetables',
    //     productName: '',
    //     brandName:'',
    //     rate: [],
    //     dicountedRate:[],
    //     offer: ,
    //     price:,
    //     discountedPrice:,
    //     weight:'',
    //     imageUrl: '',
    //     weightPakages:[],
    //     addTocardAuthendication:false,
    //     quantity:1
    // },
    // {
    //     id: 24,
    //     category:'friutsAndVegetables',
    //     productName: '',
    //     brandName:'',
    //     rate: [],
    //     dicountedRate:[],
    //     offer: ,
    //     price:,
    //     discountedPrice:,
    //     weight:'',
    //     imageUrl: '',
    //     weightPakages:[],
    //     addTocardAuthendication:false,
    //     quantity:1
    // },
    // {
    //     id: 25,
    //     category:'friutsAndVegetables',
    //     productName: '',
    //     brandName:'',
    //     rate: [],
    //     dicountedRate:[],
    //     offer: ,
    //     price:,
    //     discountedPrice:,
    //     weight:'',
    //     imageUrl: '',
    //     weightPakages:[],
    //     addTocardAuthendication:false,
    //     quantity:1
    // },
    // {
    //     id: 26,
    //     category:'friutsAndVegetables',
    //     productName: '',
    //     brandName:'',
    //     rate: [],
    //     dicountedRate:[],
    //     offer: ,
    //     price:,
    //     discountedPrice:,
    //     weight:'',
    //     imageUrl: '',
    //     weightPakages:[],
    //     addTocardAuthendication:false,
    //     quantity:1
    // },
    // {
    //     id: 27,
    //     category:'friutsAndVegetables',
    //     productName: '',
    //     brandName:'',
    //     rate: [],
    //     dicountedRate:[],
    //     offer: ,
    //     price:,
    //     discountedPrice:,
    //     weight:'',
    //     imageUrl: '',
    //     weightPakages:[],
    //     addTocardAuthendication:false,
    //     quantity:1
    // },
    // {
    //     id: 28,
    //     category:'friutsAndVegetables',
    //     productName: '',
    //     brandName:'',
    //     rate: [],
    //     dicountedRate:[],
    //     offer: ,
    //     price:,
    //     discountedPrice:,
    //     weight:'',
    //     imageUrl: '',
    //     weightPakages:[],
    //     addTocardAuthendication:false,
    //     quantity:1
    // },
    // {
    //     id: 29,
    //     category:'friutsAndVegetables',
    //     productName: '',
    //     brandName:'',
    //     rate: [],
    //     dicountedRate:[],
    //     offer: ,
    //     price:,
    //     discountedPrice:,
    //     weight:'',
    //     imageUrl: '',
    //     weightPakages:[],
    //     addTocardAuthendication:false,
    //     quantity:1
    // },
    // {
    //     id: 30,
    //     category:'friutsAndVegetables',
    //     productName: '',
    //     brandName:'',
    //     rate: [],
    //     dicountedRate:[],
    //     offer: ,
    //     price:,
    //     discountedPrice:,
    //     weight:'',
    //     imageUrl: '',
    //     weightPakages:[],
    //     addTocardAuthendication:false,
    //     quantity:1
    // },
    // {
    //     id: 31,
    //     category:'friutsAndVegetables',
    //     productName: '',
    //     brandName:'',
    //     rate: [],
    //     dicountedRate:[],
    //     offer: ,
    //     price:,
    //     discountedPrice:,
    //     weight:'',
    //     imageUrl: '',
    //     weightPakages:[],
    //     addTocardAuthendication:false,
    //     quantity:1
    // },

]